### ISSUE TITLE
Install on 8.3.1 does not work

### ISSUE THREAD

**Issue by moeetion** [mlocati/concrete5-multilingual-attributes-2#1]
Hi
I have a 8.3.1 Concrete5 installation with 4 languages. The Images should have an alt-text in this four languages. I found this package so I tried to install this put it doesn't work. (**Error:** Unable to install multilingual_attributes_i_i. Please check that this package has been updated for 5.7.) Is this package 8.3.1 ready? And does it work yet with image attributes for all installed languages?

**Comment by mlocati** [comment]
This package is only a draft: I still have to find the time to finish it.
Furthermore at the moment is only able to support single-line text fields (and even that attribute may not work).
